version: '3.9'

services:
  fastapi:
    build: .
    container_name: fastapi_app
    environment:
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./app:/app/app
      - ./alembic:/app/alembic
    command: >
      bash -c "alembic revision --autogenerate -m "Add user and refresh token tables" && alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"

  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
